import {
  MonitorSmartphone,
  Server,
  Settings,
  Sparkles,
  Cpu,
  Box,
  Disc,
  Speaker,
  Fingerprint,
  Code2,
  Languages,
  Workflow,
  Maximize,
  TerminalSquare,
} from "lucide-react";

export const iconMap: Record<string, any> = {
  frontend: MonitorSmartphone,
  backend: Server,
  devops: Settings,
  design: Sparkles,
  ai: Cpu,
  web3: Box,
  creative: Disc,
  audio: Speaker,
  hardware: Fingerprint,
  programming_languages: Code2,
  natural_languages: Languages,
  language_systems: Workflow,
  spatial: Maximize,
  tooling: TerminalSquare,
};
